from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class ZendeskService(Protocol):
    async def get_ticket(self, ticket_id: str) -> dict: ...
    async def update_ticket(self, ticket_id: str, updates: dict) -> dict: ...
    async def list_tickets(self, filters: dict | None = None) -> list[dict]: ...
    async def add_comment(self, ticket_id: str, body: str, public: bool = True) -> dict: ...


@runtime_checkable
class OrderDBService(Protocol):
    async def get_order(self, order_id: str) -> dict: ...
    async def get_orders_by_customer(self, customer_id: str) -> list[dict]: ...
    async def create_replacement_order(self, original_order_id: str, items: list[dict]) -> dict: ...


@runtime_checkable
class ShippingService(Protocol):
    async def get_tracking(self, tracking_id: str) -> dict: ...
    async def get_shipment_by_order(self, order_id: str) -> dict: ...
    async def create_return_label(self, order_id: str, items: list[dict]) -> dict: ...


@runtime_checkable
class PaymentService(Protocol):
    async def process_refund(self, transaction_id: str, amount: float, reason: str) -> dict: ...
    async def reverse_refund(self, refund_id: str) -> dict: ...
    async def get_transaction(self, transaction_id: str) -> dict: ...


@runtime_checkable
class SLARulesService(Protocol):
    async def get_policy(self, priority: str, customer_tier: str) -> dict: ...
    async def list_policies(self) -> list[dict]: ...


@runtime_checkable
class EmailService(Protocol):
    async def send_email(self, to: str, subject: str, body: str) -> dict: ...


@runtime_checkable
class IntegrationTestService(Protocol):
    async def test_endpoint(self, url: str, method: str, payload: dict | None = None) -> dict: ...
    async def run_diagnostics(self, integration_id: str) -> dict: ...
